"$schema" = "https://starship.rs/config-schema.json"

format = """
[](#9A348R)
$username\
@\
$hostname\
:$directory\
$git_branch\
$git_state\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = false

[character]
success_symbol = "[>](yellow)"
error_symbol = "[>](red)"

[username]
show_always = true
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style)"

[directory]
style = "fg:#eb6f92"

[git_branch]
style = "fg:#f6c177"
